### ISSUE TITLE
Merge PRs on upstream

### ISSUE THREAD

**Issue by mikoim** [idlemaster-ng/idlemaster-ng#4]
## can be merged
- [x] https://github.com/jshackles/idle_master/pull/268
- [x] https://github.com/jshackles/idle_master/pull/273

## review required
- [x] https://github.com/jshackles/idle_master/pull/197
- [x] https://github.com/jshackles/idle_master/pull/172

## conflicted
- [x] https://github.com/jshackles/idle_master/pull/156
- [x] https://github.com/jshackles/idle_master/pull/149

## manual commit required
- [x] https://github.com/jshackles/idle_master/pull/209

**Comment by krisser143** [comment]
We should probably add the ones that can be merged first, so we get them out of the way.

**Comment by mikoim** [comment]
Okey... I'll add them. Some PR's repositories have been deleted 😢

**Comment by krisser143** [comment]
I can work with adding the fixes manually for the missing repos

**Comment by mikoim** [comment]
I'll leave it up to you.
https://github.com/jshackles/idle_master/pull/209

**Comment by krisser143** [comment]
I'm working on that one now, just booting VS up

**Comment by krisser143** [comment]
Something is wrong with my VS, won't let me commit. Trying again

**Comment by krisser143** [comment]
Everything is now merged
